In [1]:
import pandas as pd

data = pd.read_csv("simple_data.csv")

In [2]:
type(data)

pandas.DataFrame

In [3]:
data.head() # select *n from data

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [4]:
data['price'] # select price from data
type(data['price'] )
data['price'] # select avg(price) from data

0     12.99
1     15.49
2    199.99
3     29.99
4     99.99
Name: price, dtype: float64

In [5]:
data[['price','rating']].describe()

          price    rating
count    5.0000  5.000000
mean    71.6900  4.240000
std     80.0075  0.559464
min     12.9900  3.500000
25%     15.4900  4.000000
50%     29.9900  4.200000
75%     99.9900  4.500000
max    199.9900  5.000000

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  5 non-null      str
 1   price             5 non-null      float64
 2   rating            5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

In [7]:
import numpy as np
data = {
    'orderId':[1,2,3,4,5],
    'delivery_time':[30,45,20,35,50],
    'customer_feedback':[np.nan,4.5,3.0,4.0,np.nan]
}

df = pd.DataFrame(data)
df.head(2)

   orderId  delivery_time  customer_feedback
0        1             30                NaN
1        2             45                4.5

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   orderId            5 non-null      int64
 1   delivery_time      5 non-null      int64
 2   customer_feedback  3 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 252.0 bytes

In [9]:
df.isnull().sum()

orderId              0
delivery_time        0
customer_feedback    2
dtype: int64

In [10]:
import numpy as np
data = {
    'age': np.random.randint(0, 100, 500),
    'income': np.random.randint(20000, 100000, 500),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 500)
}


customer_data = pd.DataFrame(data)
customer_data.head()

   age  income         city
0   35   21874     New York
1   28   68500      Houston
2   33   98104     New York
3   22   74147  Los Angeles
4   18   80898      Phoenix

In [11]:
customer_data.city.value_counts()

city
Los Angeles    111
Phoenix        107
New York       101
Chicago         91
Houston         90
Name: count, dtype: int64

In [12]:
customer_data.shape

(500, 3)

In [13]:
customer_data.groupby('city')['income'].max()

city
Chicago        98500
Houston        96741
Los Angeles    99554
New York       99239
Phoenix        97881
Name: income, dtype: int64

In [14]:
customer_data.groupby('city').agg({
    'income': ['max', 'min', 'mean']
})

            income
               max    min          mean
city
Chicago      98500  21182  61418.219780
Houston      96741  20566  56961.688889
Los Angeles  99554  21803  61165.369369
New York     99239  20005  57776.980198
Phoenix      97881  20663  60187.457944

In [15]:
data = {
    'age': np.random.randint(0, 100, 500),
    'income': np.random.randint(20000, 100000, 500),
    'price': np.random.randint(5, 500, 500),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 500),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Groceries', 'Books', 'Furniture'], 500)
}


sales_df = pd.DataFrame(data)

sales_df.head(2)

   age  income  price      city product_category
0   51   66626    163   Chicago         Clothing
1   90   97693    228  New York        Groceries

In [16]:
sales_df.groupby('city').agg({
    'income': ['max', 'min', 'mean'],
    'price': ['max', 'min', 'mean']
})

            income                      price
               max    min          mean   max min        mean
city
Chicago      99714  21052  62800.660000   498   5  221.960000
Houston      99551  20025  57316.130435   490   7  233.510870
Los Angeles  99645  20480  63251.546392   494   5  246.195876
New York     99579  20079  59540.478992   498  12  257.378151
Phoenix      99510  20049  60278.206522   498  34  280.869565

In [17]:
sales_df.groupby(['city', 'product_category']).agg({
    'price': ['max', 'min', 'mean','std']
})

                             price
                               max  min        mean         std
city        product_category
Chicago     Books              464    5  181.300000  121.336461
            Clothing           476   11  210.533333  165.217548
            Electronics        498    5  264.588235  183.897410
            Furniture          491    6  209.904762  163.967956
            Groceries          471   27  240.962963  137.364893
Houston     Books              421   22  208.947368  130.330125
            Clothing           473    7  241.882353  147.105354
            Electronics        442    8  198.363636  141.242967
            Furniture          490  111  282.050000  119.422944
            Groceries          478   31  242.571429  139.390825
Los Angeles Books              494    6  237.600000  155.897537
            Clothing           443    8  190.333333  137.519938
            Electronics        468   15  229.307692  176.856055
            Furniture          474    5  275.304348  135.322992
            Groceries          472   31  290.950000  150.158679
New York    Books              493   12  252.000000  136.316397
            Clothing           485   22  257.933333  181.034514
            Electronics        498   54  267.421053  152.450107
            Furniture          494   21  271.000000  136.544442
            Groceries          470   12  244.031250  143.382746
Phoenix     Books              487   62  292.350000  135.494135
            Clothing           498   34  267.526316  133.250544
            Electronics        433   35  226.352941  113.832081
            Furniture          472   59  293.562500  133.282141
            Groceries          493   35  318.250000  142.969218

In [18]:
# in groupby : agg function : you can also pass 
def range_func(x):
    return x.max() - x.min()

result_df = sales_df.groupby(['city', 'product_category']).agg({
    'price': ['max', 'min', 'mean', range_func]
})

# order by
result_df = result_df.sort_values(by=('price', 'mean'), ascending=False)
result_df.head(10)

                             price
                               max  min        mean range_func
city        product_category
Phoenix     Groceries          493   35  318.250000        458
            Furniture          472   59  293.562500        413
            Books              487   62  292.350000        425
Los Angeles Groceries          472   31  290.950000        441
Houston     Furniture          490  111  282.050000        379
Los Angeles Furniture          474    5  275.304348        469
New York    Furniture          494   21  271.000000        473
Phoenix     Clothing           498   34  267.526316        464
New York    Electronics        498   54  267.421053        444
Chicago     Electronics        498    5  264.588235        493

In [19]:
result_df.to_csv('sales_analysis.csv')

In [20]:
result_df.to_html('sales_analysis.html')

In [21]:
type(result_df)

pandas.DataFrame

In [22]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[5, 6, 7, 8],
)

final_df = pd.concat([df1, df2],axis=1) #if axis=0 = row-wise concatenation else column-wise
final_df

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A4   B4   C4   D4
6  NaN  NaN  NaN  NaN   A5   B5   C5   D5
7  NaN  NaN  NaN  NaN   A6   B6   C6   D6
8  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [27]:
# sales table vs product table
sales_df = pd.DataFrame({
    'order_id': [1, 2, 3],
    'product_id': [101, 102, 103],
    'quantity': [2, 1, 5]
})

product_df = pd.DataFrame({
    'product_id': [101, 102, 103],
    'product_name': ['Product A', 'Product B', 'Product C'],
    'price': [10.0, 20.0, 30.0]
} )

In [25]:
sales_df.head()

   order_id  product_id  `quantity`
0         1         101           2
1         2         102           1
2         3         103           5

In [26]:
product_df.head()

   product_id product_name  price
0         101    Product A   10.0
1         102    Product B   20.0
2         103    Product C   30.0

In [30]:
final_table = pd.merge(sales_df, product_df[['product_id', 'price']], on='product_id', how='left') # left join

In [32]:
final_table.head(2)
final_table['total_price'] = final_table['quantity'] * final_table['price']

In [34]:
final_table.total_price.describe()

count      3.000000
mean      63.333333
std       75.055535
min       20.000000
25%       20.000000
50%       20.000000
75%       85.000000
max      150.000000
Name: total_price, dtype: float64

In [35]:
# sometime col name may differ in both dataframe
# ex
sales_df = pd.DataFrame({
    'order_id': [1, 2, 3],
    'product_id': [101, 102, 103],
    'quantity': [2, 1, 5]
})

product_df = pd.DataFrame({
    'id': [101, 102, 103],
    'product_name': ['Product A', 'Product B', 'Product C'],
    'price': [10.0, 20.0, 30.0]
} )


pd.merge(sales_df, product_df[['id', 'price']], left_on='product_id', right_on='id', how='left')

   order_id  product_id  quantity   id  price
0         1         101         2  101   10.0
1         2         102         1  102   20.0
2         3         103         5  103   30.0

In [40]:
sales_df = pd.DataFrame({
    'order_id': [1, 2, 3],
    'product_id': [101, 102, 103],
    'quantity': [2, 1, 5]
})

product_df = pd.DataFrame({
    'product_id': [101, 102, 103],
    'product_name': ['Product A', 'Product B', 'Product C'],
    'price': [10.0, 20.0, 30.0]
} )

sales_df.head()

   order_id  product_id  quantity
0         1         101         2
1         2         102         1
2         3         103         5

In [42]:
sales_df.join(product_df.set_index('product_id'), on='product_id', how='left')

   order_id  product_id  quantity product_name  price
0         1         101         2    Product A   10.0
1         2         102         1    Product B   20.0
2         3         103         5    Product C   30.0

In [ ]:
# when to use merge and join ??
# Use merge when you need to combine DataFrames based on a key column(s) and you want to specify
#  how to handle overlapping columns.
# Use join when you want to combine DataFrames based on their index or a key column(s) 
# and you want a simpler syntax.